{% set name = "troposphere" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2f29692ab549ea21861e0320a9d9e6432b23d784de6c9c29b40da27512f94e17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cfn-flip >=1.0.2
    - awacs >=0.8
    - python >=3.6

test:
  imports:
    - troposphere
    - troposphere.helpers
    - troposphere.openstack
  requires:
    - awacs >=0.8

about:
  home: https://github.com/cloudtools/troposphere
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS CloudFormation creation library
  doc_url: https://troposphere.readthedocs.io
  dev_url: https://github.com/cloudtools/troposphere

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
