{% set name = "troposphere" %}
{% set version = "4.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f39f882789cb9867b01787d204d39a924c033e0e14c7f825dbaccb560405aa2d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cfn-flip >=1.0.2
    - awacs >=0.8
    - python >=3.6

test:
  imports:
    - troposphere
    - troposphere.helpers
    - troposphere.openstack
  requires:
    - awacs >=0.8

about:
  home: https://github.com/cloudtools/troposphere
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS CloudFormation creation library
  doc_url: https://troposphere.readthedocs.io
  dev_url: https://github.com/cloudtools/troposphere

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
