{% set name = "troposphere" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 71f4d6623b44ed71c0dbd9d7698784a9c0de14d3a05ce086cd5c827a6d276ab3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - cfn-flip >=1.0.2
    - awacs >=0.8
    - python

test:
  imports:
    - troposphere
    - troposphere.helpers
    - troposphere.openstack
  requires:
    - awacs >=0.8

about:
  home: https://github.com/cloudtools/troposphere
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS CloudFormation creation library
  doc_url: https://troposphere.readthedocs.io
  dev_url: https://github.com/cloudtools/troposphere

extra:
  recipe-maintainers:
    - mxr-conda
    - agcopenhaver
    - adbeda
    - rluria14
    - oblute
